name: Make changelogs

on:
  push:
    branches:
    - dev

jobs:
  MakeCL:
    runs-on: ubuntu-latest
    if: github.repository == '4310V343k/Proxi-Bay12' # to prevent this running on forks
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          fetch-depth: 25
      - name: Setup and cache python and dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
        run: pip install ruamel.yaml PyGithub
      - name: Make CL
        id: make-cl
        run: |
          python tools/changelog/generate_cl.py
          echo ::set-output name=pr_number::${PR_NUM}
      - name: Commit and Push Changes
        if: steps.make-cl.outputs.pr_number != '-1'
        run: |
          git config --local user.name "Changelogs"
          git config --local user.email "action@github.com"
          git add .
          git commit -m "Automatic changelog generation for PR #${{ steps.make-cl.outputs.pr_number }} [ci skip]"
          git push
